const ruDays=['вс','пн','вт','ср','чт','пт','сб'];
const ruMonths=['января','февраля','марта','апреля','мая','июня','июля','августа','сентября','октября','ноября','декабря'];
const shows=[
  {name:'Чайка',dateOffset:2,time:'19:00',place:'Большая сцена',cast:['АС','МВ','ИК','ОЛ','+4'],conflict:1},
  {name:'Гроза',dateOffset:6,time:'18:30',place:'Камерная сцена',cast:['ДП','АС','ЕН','+3'],conflict:0},
  {name:'Три сестры',dateOffset:10,time:'19:00',place:'Большая сцена',cast:['КС','МВ','ОЛ','+6'],conflict:2}
];
const members=[
  {name:'Анна Смирнова',role:'Актриса',shows:['Чайка','Гроза'],week:['free','free','limited','busy','free','free','none']},
  {name:'Михаил Волков',role:'Актёр',shows:['Чайка','Три сестры'],week:['free','busy','free','free','limited','free','free']},
  {name:'Ирина Крылова',role:'Актриса',shows:['Чайка'],week:['free','free','free','busy','busy','free','none']},
  {name:'Денис Петров',role:'Актёр',shows:['Гроза'],week:['limited','free','free','free','free','busy','busy']},
  {name:'Ольга Левина',role:'Актриса',shows:['Чайка','Три сестры'],week:['free','free','busy','free','free','free','limited']}
];
const state={user:JSON.parse(localStorage.getItem('sbor-user')||'null'),availability:JSON.parse(localStorage.getItem('sbor-availability')||'{}'),admin:false,selectedDate:null,selectedStatus:null,filter:'Все'};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const fmt=d=>`${d.getDate()} ${ruMonths[d.getMonth()]}`;
function dateAt(offset){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+offset);return d}
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function initDefaults(){if(Object.keys(state.availability).length)return;['free','free','limited','busy','free','none','free','free','limited','free','busy','none','free','free'].forEach((s,i)=>{if(s!=='none')state.availability[iso(dateAt(i))]={status:s,...(s==='limited'?{from:'18:00',to:'22:00'}:{})}});persist()}
function persist(){localStorage.setItem('sbor-availability',JSON.stringify(state.availability))}
function login(user={name:'Анна Смирнова',role:'Актриса'}){state.user=user;localStorage.setItem('sbor-user',JSON.stringify(user));$('#authScreen').classList.add('hidden');$('#app').classList.remove('hidden');applyUser();renderAll()}
function applyUser(){const n=state.user?.name||'Анна Смирнова';$('#profileName').textContent=n;$('#profileRole').textContent=state.user?.role||'Участник';$('#avatar').textContent=n.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function renderCalendar(){const cal=$('#calendar');cal.innerHTML='';for(let i=0;i<14;i++){const d=dateAt(i), key=iso(d), av=state.availability[key], show=shows.find(s=>s.dateOffset===i);const el=document.createElement('article');el.className=`day ${i===0?'today':''}`;el.dataset.date=key;let status='<div class="status-pill status-none">+ отметить</div>';if(av){const labels={free:'Свободен',limited:'С ограничениями',busy:'Не могу'};status=`<div class="status-pill status-${av.status}">${labels[av.status]}${av.from?`<small>${av.from}–${av.to}</small>`:''}</div>`}el.innerHTML=`<div class="day-head"><span class="weekday">${ruDays[d.getDay()]}</span><span class="date-num">${d.getDate()}</span></div>${show?`<div class="event-marker">${show.time}<br>${show.name}</div>`:''}${status}`;el.onclick=()=>openDay(key);cal.appendChild(el)}}
function renderEvents(){const box=$('#eventList');box.innerHTML=shows.map(s=>{const d=dateAt(s.dateOffset);return `<article class="event-card"><div class="event-date">${String(d.getDate()).padStart(2,'0')}.${String(d.getMonth()+1).padStart(2,'0')}</div><div class="event-main"><strong>${s.name}</strong><span>${s.time} · ${s.place}</span></div><div class="event-meta">${s.conflict?`<span class="warning">${s.conflict} ${s.conflict===1?'участник не может':'участника не могут'}</span>`:'Весь состав свободен'}</div></article>`}).join('')}
function renderShows(){const box=$('#showGrid');box.innerHTML=shows.map((s,i)=>`<article class="show-card"><span class="show-card-number">0${i+1} / ${fmt(dateAt(s.dateOffset))}</span><h3>${s.name}</h3><p>${s.time} · ${s.place}</p><div class="cast-avatars">${s.cast.map(x=>`<span>${x}</span>`).join('')}</div><div class="show-status"><span>Состав: ${s.cast.length+3} человек</span><span class="${s.conflict?'warning':''}">${s.conflict?s.conflict+' не могут':'Все свободны'}</span></div></article>`).join('')}
function renderTeam(){const names=['Все',...shows.map(s=>s.name)];$('#filters').innerHTML=names.map(n=>`<button class="filter ${state.filter===n?'active':''}" data-filter="${n}">${n}</button>`).join('');$$('.filter').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;renderTeam()});const filtered=members.filter(m=>state.filter==='Все'||m.shows.includes(state.filter));$('#teamTable').innerHTML=filtered.map(m=>`<tr><td><div class="person"><span class="mini-avatar">${m.name.split(' ').map(x=>x[0]).join('')}</span><span><strong>${m.name}</strong><br><small>${m.role}</small></span></div></td><td>${m.shows.join(', ')}</td><td><div class="week-dots">${m.week.map(s=>`<i class="${s==='none'?'gray':s==='free'?'green':s==='limited'?'yellow':'red'}"></i>`).join('')}</div></td><td class="admin-only"><button class="small-action">Изменить состав</button></td></tr>`).join('')}
function renderAll(){initDefaults();renderCalendar();renderEvents();renderShows();renderTeam();const now=new Date();$('#todayLabel').textContent=`${ruDays[now.getDay()]}, ${fmt(now)}`}
function openDay(key){state.selectedDate=key;const d=new Date(key+'T12:00:00'),av=state.availability[key];state.selectedStatus=av?.status||null;$('#modalDate').textContent=`${d.getDate()} ${ruMonths[d.getMonth()]}, ${ruDays[d.getDay()]}`;$$('[data-status]').forEach(b=>b.classList.toggle('selected',b.dataset.status===state.selectedStatus));$('#timeFields').classList.toggle('hidden',state.selectedStatus!=='limited');if(av?.from){$('#timeFrom').value=av.from;$('#timeTo').value=av.to}$('#dayModal').classList.remove('hidden')}
function toast(t='Сохранено'){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
$$('.auth-tab').forEach(b=>b.onclick=()=>{$$('.auth-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#loginForm').classList.toggle('hidden',b.dataset.authTab!=='login');$('#registerForm').classList.toggle('hidden',b.dataset.authTab!=='register')});
$('#loginButton').onclick=()=>login();$('#demoButton').onclick=()=>login();$('#registerButton').onclick=()=>{const name=$('#registerName').value.trim();if(!name||!$('#registerEmail').value.includes('@')||$('#registerPassword').value.length<8){toast('Заполните все поля');return}login({name,role:'Участник'})};
$('#logoutButton').onclick=()=>{localStorage.removeItem('sbor-user');location.reload()};
$$('.nav-link').forEach(b=>b.onclick=()=>{$$('.nav-link').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(p=>p.classList.remove('active'));$(`#${b.dataset.page}Page`).classList.add('active');$('#pageTitle').textContent={schedule:'Моя доступность',shows:'Спектакли',team:'Участники'}[b.dataset.page];$('.sidebar').classList.remove('open')});
$$('[data-go]').forEach(b=>b.onclick=()=>document.querySelector(`[data-page="${b.dataset.go}"]`).click());
$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');
$('#adminToggle').onclick=()=>{state.admin=!state.admin;$('#app').classList.toggle('admin-mode',state.admin);$('#adminToggle span:last-child').innerHTML=`<small>Режим</small>${state.admin?'Администратор':'Участник'}`;$('#profileRole').textContent=state.admin?'Администратор':state.user.role;toast(state.admin?'Режим администратора':'Режим участника')};
$$('[data-status]').forEach(b=>b.onclick=()=>{state.selectedStatus=b.dataset.status;$$('[data-status]').forEach(x=>x.classList.toggle('selected',x===b));$('#timeFields').classList.toggle('hidden',state.selectedStatus!=='limited')});
$('#saveDay').onclick=()=>{if(!state.selectedStatus){toast('Выберите статус');return}state.availability[state.selectedDate]={status:state.selectedStatus,...(state.selectedStatus==='limited'?{from:$('#timeFrom').value,to:$('#timeTo').value}:{})};persist();$('#dayModal').classList.add('hidden');renderCalendar();toast()};
$$('[data-close]').forEach(b=>b.onclick=()=>$('#dayModal').classList.add('hidden'));$('#dayModal').onclick=e=>{if(e.target.id==='dayModal')e.currentTarget.classList.add('hidden')};
$('#copyWeek').onclick=()=>{for(let i=0;i<7;i++){const a=state.availability[iso(dateAt(i))];if(a)state.availability[iso(dateAt(i+7))]={...a}}persist();renderCalendar();toast('Неделя скопирована')};
$('#addShow').onclick=()=>toast('Форма создания — следующий экран прототипа');
if(state.user)login(state.user);
