-- Схема для следующего этапа подключения Supabase.
create table profiles (id uuid primary key references auth.users on delete cascade, full_name text not null, role text default 'member', created_at timestamptz default now());
create table productions (id bigint generated by default as identity primary key, title text not null, venue text, starts_at timestamptz not null, created_by uuid references profiles(id));
create table production_members (production_id bigint references productions on delete cascade, user_id uuid references profiles on delete cascade, primary key (production_id,user_id));
create table availability (id bigint generated by default as identity primary key, user_id uuid references profiles on delete cascade, day date not null, status text check (status in ('free','limited','busy')), available_from time, available_to time, unique(user_id,day));
